### ISSUE TITLE
Pas de bouton "page suivante" sur de nombreuses pages (TF1, TMC)

### ISSUE THREAD

**Issue by tug912** [spmjc/plugin.video.freplay#103]
Bonjour,

C'est certe un détail mais ca oblige/empêche de voir des replay plus vieux de qq jours alors qu'ils sont bien présents sur le site.
De plus l'option "afficher les bonus" ne fonctionne pas lorsqu'on la décoche on obtient la même chose.

Merci par avance et bon courage pr la prochaine up

**Comment by spmjc** [comment]
L add-on utilise les API. Je ne crois pas qu'il y ait possibilité de
remonter plus loin.

On Jun 15, 2017 6:03 PM, "tug912" <notifications@github.com> wrote:

Bonjour,

C'est certe un détail mais ca oblige/empêche de voir des replay plus vieux
de qq jours alors qu'ils sont bien présents sur le site.
De plus l'option "afficher les bonus" ne fonctionne pas lorsqu'on la
décoche on obtient la même chose.

Merci par avance et bon courage pr la prochaine up

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/spmjc/plugin.video.freplay/issues/103>, or mute the
thread
